package nodes

import (
	"fmt"
	"strings"

	"github.com/kemilad/karpx/internal/kube"
)

// GenerateManifest returns the YAML string for the NodePool (and NodeClass)
// that implements the given Recommendation.
//
// clusterName and roleARN are AWS-specific; they are ignored for other providers.
func GenerateManifest(r Recommendation, clusterName, roleARN string) string {
	switch r.Provider {
	case kube.ProviderAWS:
		return generateAWSManifest(r, clusterName, roleARN)
	case kube.ProviderAzure:
		return generateAzureManifest(r)
	case kube.ProviderGCP:
		return generateGCPManifest(r)
	default:
		return "# Provider not supported — no manifest generated\n"
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// AWS EKS — NodePool + EC2NodeClass
// ─────────────────────────────────────────────────────────────────────────────

func generateAWSManifest(r Recommendation, clusterName, roleARN string) string {
	if clusterName == "" {
		clusterName = "<CLUSTER_NAME>"
	}
	if roleARN == "" {
		roleARN = "<KARPENTER_NODE_ROLE_ARN>"
	}

	families := quotedList(r.InstanceFamilies)
	capacities := quotedList(r.CapacityTypes)
	archs := quotedList(r.Architectures)
	cpus := quotedList(r.CPUSizes)

	// Mode-specific consolidation settings.
	consolidateAfter := "1m"
	consolidationPolicy := "WhenEmptyOrUnderutilized"
	if r.Mode == ModeHighPerformance {
		consolidateAfter = "5m"
		consolidationPolicy = "WhenEmpty"
	}

	// Header comment describes what karpx chose and why.
	header := fmt.Sprintf(`# ──────────────────────────────────────────────────────────────────────────
# Generated by karpx
# Mode         : %s
# Workload     : %s
# Provider     : AWS EKS
#
# Why these instance families:
%s
# ──────────────────────────────────────────────────────────────────────────
`,
		modeLabel(r.Mode),
		string(r.WorkloadType),
		commentLines(r.Reasoning),
	)

	nodepool := fmt.Sprintf(`apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: karpx-default
  annotations:
    karpx.io/generated-mode: "%s"
    karpx.io/workload-type: "%s"
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: karpx-default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: [%s]
        - key: kubernetes.io/arch
          operator: In
          values: [%s]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: [%s]
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values: [%s]
        - key: karpenter.k8s.aws/instance-memory
          operator: Gt
          values: ["%d"]
  limits:
    cpu: "1000"
    memory: 4000Gi
  disruption:
    consolidationPolicy: %s
    consolidateAfter: %s
`,
		string(r.Mode),
		string(r.WorkloadType),
		capacities,
		archs,
		families,
		cpus,
		r.MinNodeMiB,
		consolidationPolicy,
		consolidateAfter,
	)

	nodeclass := fmt.Sprintf(`---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: karpx-default
spec:
  amiSelectorTerms:
    - alias: al2023@latest
  role: "%s"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "%s"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "%s"
  tags:
    ManagedBy: karpx
    OptimizationMode: "%s"
`, roleARN, clusterName, clusterName, string(r.Mode))

	return header + nodepool + nodeclass
}

// ─────────────────────────────────────────────────────────────────────────────
// Azure AKS — NodePool + AKSNodeClass
// ─────────────────────────────────────────────────────────────────────────────

func generateAzureManifest(r Recommendation) string {
	families := quotedList(r.InstanceFamilies)
	capacities := quotedList(r.CapacityTypes)

	header := fmt.Sprintf(`# ──────────────────────────────────────────────────────────────────────────
# Generated by karpx
# Mode         : %s
# Workload     : %s
# Provider     : Azure AKS (preview — karpenter-provider-azure-aks)
#
%s
# ──────────────────────────────────────────────────────────────────────────
`,
		modeLabel(r.Mode),
		string(r.WorkloadType),
		commentLines(r.Reasoning),
	)

	nodepool := fmt.Sprintf(`apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: karpx-default
spec:
  template:
    spec:
      nodeClassRef:
        apiVersion: karpenter.azure.com/v1alpha2
        kind: AKSNodeClass
        name: karpx-default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: [%s]
        - key: karpenter.azure.com/sku-family
          operator: In
          values: [%s]
        - key: karpenter.azure.com/sku-cpu
          operator: In
          values: [%s]
  limits:
    cpu: "1000"
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
---
apiVersion: karpenter.azure.com/v1alpha2
kind: AKSNodeClass
metadata:
  name: karpx-default
spec:
  imageFamily: AzureLinux
`,
		capacities,
		families,
		quotedList(r.CPUSizes),
	)

	return header + nodepool
}

// ─────────────────────────────────────────────────────────────────────────────
// GCP GKE — NodePool + GCENodeClass
// ─────────────────────────────────────────────────────────────────────────────

func generateGCPManifest(r Recommendation) string {
	families := quotedList(r.InstanceFamilies)
	capacities := quotedList(r.CapacityTypes)

	header := fmt.Sprintf(`# ──────────────────────────────────────────────────────────────────────────
# Generated by karpx
# Mode         : %s
# Workload     : %s
# Provider     : GCP GKE (experimental — karpenter-provider-gcp)
#
%s
# ──────────────────────────────────────────────────────────────────────────
`,
		modeLabel(r.Mode),
		string(r.WorkloadType),
		commentLines(r.Reasoning),
	)

	nodepool := fmt.Sprintf(`apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: karpx-default
spec:
  template:
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.gcp/v1
        kind: GCENodeClass
        name: karpx-default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: [%s]
        - key: cloud.google.com/machine-family
          operator: In
          values: [%s]
  limits:
    cpu: "1000"
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
---
apiVersion: karpenter.k8s.gcp/v1
kind: GCENodeClass
metadata:
  name: karpx-default
spec:
  # Fill in your GCP project / image configuration
  # See: https://github.com/kubernetes-sigs/karpenter-provider-gcp#readme
`,
		capacities,
		families,
	)

	return header + nodepool
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

func quotedList(items []string) string {
	quoted := make([]string, len(items))
	for i, v := range items {
		quoted[i] = `"` + v + `"`
	}
	return strings.Join(quoted, ", ")
}

func commentLines(lines []string) string {
	var b strings.Builder
	for _, l := range lines {
		b.WriteString("# • ")
		b.WriteString(l)
		b.WriteString("\n")
	}
	return b.String()
}

func modeLabel(m OptimizationMode) string {
	switch m {
	case ModeCostOptimized:
		return "Cost-Optimized (Spot + Graviton where available)"
	case ModeHighPerformance:
		return "High-Performance (On-Demand, latest-gen, no Spot)"
	default:
		return "Balanced (Spot + On-Demand, mixed families)"
	}
}
